# Generated by Django 4.1.5 on 2023-09-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
