# Generated by Django 4.1.5 on 2023-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='ip',
            field=models.CharField(max_length=100, unique=True, verbose_name='IP-адрес'),
        ),
    ]
