# Generated by Django 4.1.5 on 2023-10-02 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_likes_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dats',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 11, 49, 13, 590026)),
        ),
    ]
