# Generated by Django 4.1.5 on 2023-10-02 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_post_dats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compos', to='users.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dats',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 16, 49, 6, 255488)),
        ),
    ]
