# Generated by Django 4.1.5 on 2023-10-04 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_comments_post_alter_post_dats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=100, verbose_name='Имя режисёра')),
            ],
        ),
        migrations.CreateModel(
            name='Dressingroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, verbose_name='Номсер гримёрки')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='dats',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 11, 2, 43, 967711)),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя актёра')),
                ('direc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.director')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя актёра')),
                ('dress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.dressingroom')),
                ('mov', models.ManyToManyField(to='users.movie')),
            ],
        ),
    ]
